refactor: timeline
galacean/effects-specification pull request #9
Opened 2024-03-28 11:56 UTC by wumaolinmaoan

2024-04-01 07:04 UTC, yiiqii requested changes

2024-04-01 07:04 UTC, yiiqii commented on src/item/model/material.ts
> +  additive = 103, // 叠
这个注释的改动是特意的？

2024-04-02 05:21 UTC, wumaolinmaoan commented on src/item/model/material.ts
> +  additive = 103, // 叠
误删了

2024-04-02 05:37 UTC, wumaolinmaoan commented on src/item/model/material.ts
> +  additive = 103, // 叠
已修改

2024-04-02 06:08 UTC, merged